#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
CREATE USER hiwa WITH PASSWORD 'hiwa';
CREATE DATABASE hiwa WITH ENCODING 'utf-8' OWNER hiwa;
GRANT ALL PRIVILEGES ON DATABASE hiwa TO hiwa;
GRANT CONNECT ON DATABASE hiwa TO hiwa;
EOSQL
