INSTDIR=/var/www/html/hiwa

.phony: installcss installimg install

none:
	echo "Not doing anything unless told what."

installcss:
	cp *.css  ${INSTDIR}

installimg:
	cp *.png ${INSTDIR}
	
install: installcss installimg
	
